spring.application.name=drakes

spring.datasource.url=jdbc:mysql://tccsenai-osdrakedosenai.f.aivencloud.com:16812/tcc
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_K_Y4nR5Y098mcXNujOn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
