spring.application.name=drakes

#spring.datasource.url=jdbc:mysql://tcc-osdrakedosenai.i.aivencloud.com:16812/tcc
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_ObIznIPfJjawsZ3bbzM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/tcc
spring.datasource.username=root
spring.datasource.password=root

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=osdrakedosenai@gmail.com
spring.mail.password=rpsd qfki stdb gtzy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

validation.allowed-domains=gmail.com,outlook.com,hotmail.com,senai.com

relatorios.diretorio.base=C:/Users/SEDUC DEST1/Documents/relatorios

logging.level.org.springframework.security=DEBUG